'use client';
import { useEffect, useState } from 'react';
import { ArrowDown, ArrowUpRight, Badge, LockKeyhole, Users } from 'lucide-react';
import { Progress } from '@/components/ui/progress';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { campaign } from '@/config/campaign';
type Stats={count:number;foundingRemaining:number;leaders:{id:number;number:string;handle:string;recruits:number;rank:number}[];treasury:{totalCents:number;richCents:number;poorCents:number};updatedAt:string};
export function PublicRecords() {
 const [stats,setStats]=useState<Stats|null>(null),[failed,setFailed]=useState(false);
 useEffect(()=>{let mounted=true;const refresh=async()=>{if(document.visibilityState==='hidden')return;try{const r=await fetch('/api/registry?view=public');const data=await r.json() as {stats:Stats};if(!r.ok)throw new Error();if(mounted){setStats(data.stats);setFailed(false);}}catch{if(mounted)setFailed(true);}};void refresh();const interval=setInterval(refresh,60000);window.addEventListener('sheriff-registry-updated',refresh);return()=>{mounted=false;clearInterval(interval);window.removeEventListener('sheriff-registry-updated',refresh);};},[]);
 return <><section className="record-strip wrap"><div><Users size={22}/><strong>{stats?stats.count.toLocaleString():'—'}</strong><span>DEPUTIES HAVE ENTERED<br/>THE JURISDICTION</span></div><div><Badge size={22}/><strong>{stats?stats.foundingRemaining:'—'}<small>/{campaign.foundingLimit}</small></strong><span>FOUNDING BADGES<br/>STILL UNISSUED</span></div></section>
 <section className="leaderboard-section wrap" id="leaderboard"><div className="section-heading"><div><p className="eyebrow muted">02 / PUBLIC RECORDS</p><h2>The Sheriff’s<br/>most wanted.</h2></div><p>Recruit the next Deputy.<br/>Earn your place in the records.</p></div><div className="leaderboard-frame"><div className="board-label"><span>TOP DEPUTIES / BY RECRUITS</span><span className="data-status"><span className="status-dot"/>{failed?'UPDATE UNAVAILABLE':stats?'REGISTRY RECORDS':'OPENING RECORDS'}</span></div>{stats?.leaders.length?<Table><TableHeader><TableRow><TableHead>RANK</TableHead><TableHead>DEPUTY</TableHead><TableHead>X USERNAME</TableHead><TableHead className="number-cell">RECRUITS</TableHead></TableRow></TableHeader><TableBody>{stats.leaders.map(d=><TableRow key={d.id}><TableCell>#{d.rank}</TableCell><TableCell className="accent">#{d.number}</TableCell><TableCell>@{d.handle}</TableCell><TableCell className="number-cell">{d.recruits}</TableCell></TableRow>)}</TableBody></Table>:<div className="empty-records"><Badge size={38} strokeWidth={1}/><h3>{failed&&!stats?'The records are taking a moment.':stats?'The board is waiting for its first name.':'Opening the public records…'}</h3><p>{failed&&!stats?'Please return shortly. We’ll show the records when the Registry is available.':'A place here is earned with recruits. Make your first introduction.'}</p><a href="#registry" className="text-link">APPLY FOR A BADGE<ArrowUpRight size={14}/></a></div>}{stats&&<div className="record-note">{failed?'Showing the last available records. ':''}UPDATED {new Date(stats.updatedAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})} · RECRUITS COUNT WHEN A BADGE IS ISSUED.</div>}</div></section>
 <section className="coming-tax"><div className="wrap"><div className="coming-title"><p className="eyebrow">03 / THE COMING TAX</p><h2>First they tax<br/><em>the rich.</em></h2><p>One experiment. Two jurisdictions.<br/>A very unusual collection notice.</p></div><div className="phase-cards"><article className="phase-card rich"><div className="phase-label"><span>PHASE I</span><span>NOT YET OPEN</span></div><h3>TAX THE RICH</h3><strong className="phase-target">$75,000</strong><p>JURISDICTION TARGET</p><div className="phase-band"><span>CONTRIBUTION BAND</span><strong>$750–$2,500</strong></div></article><article className="phase-card poor"><div className="phase-label"><span>PHASE II</span><span><LockKeyhole size={13}/> LOCKED</span></div><h3>TAX THE POOR</h3><strong className="phase-target">$25,000</strong><p>JURISDICTION TARGET</p><div className="phase-band"><span>CONTRIBUTION BAND</span><strong>$25–$250</strong></div><small>Unlocks after Phase I reaches $75,000.</small></article></div><div className="master-target"><div><span className="eyebrow">THE EXPERIMENT</span><strong>$100,000</strong></div><p>Voluntarily paid.<br/>No financial return promised.</p><ArrowDown size={25}/></div><div className="treasury-line"><span>TOTAL TAX COLLECTED</span><strong>{stats?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(stats.treasury.totalCents/100):'—'} <small>/ $100,000</small></strong></div><Progress value={stats?Math.min(100,stats.treasury.totalCents/campaign.totalTargetCents*100):0} aria-label="Total tax collected toward the experiment target"/><p className="treasury-note">Tax Season has not begun. Planned assets: ETH + USDG on Robinhood Chain.</p></div></section></>;
}
