import { ArrowDown, ArrowUpRight, Badge, Star } from 'lucide-react';
import { RegistryPanel } from '@/components/registry-panel';
import { PublicRecords } from '@/components/public-records';
export default function SiteHome() {
return <><div className="notice-bar"><span>VOLUNTARY TAXATION</span><span>JURISDICTION: THE ENTIRE TIMELINE</span></div>
<header className="site-header wrap"><a className="wordmark" href="/" aria-label="The Sheriff's Tax home"><Badge/><span>THE SHERIFF’S TAX<small>DECENTRALIZED REVENUE SERVICE</small></span></a><nav aria-label="Main navigation"><a href="#registry">THE REGISTRY</a><a href="#tax-code">TAX CODE</a><a href="https://x.com/sheriffstax" target="_blank" rel="noreferrer">𝕏<span className="sr-only">The Sheriff on X</span></a></nav></header>
<main><section className="hero wrap"><div><p className="eyebrow"><span className="status-dot"/>TAX SEASON: NOT YET OPEN</p><h1>CONGRATULATIONS.<br/>YOU’RE BEING<br/><em>TAXED.</em></h1><p className="hero-description">Can the internet voluntarily pay The Sheriff <strong>$100,000</strong> with no promised financial return?</p><div className="hero-actions"><a className="button primary" href="#registry">APPLY FOR A BADGE <ArrowUpRight size={20}/></a><a className="text-link" href="#tax-code">READ THE TAX CODE <ArrowDown size={15}/></a></div><p className="microcopy">FREE TO JOIN. NO WALLET REQUIRED. A BADGE HAS TO BE EARNED.</p></div>
<aside className="wanted-card"><div className="paper-overline"><span>OFFICIAL RECRUITMENT NOTICE</span><span>No. 001</span></div><div className="wanted-title">WANTED</div><p className="wanted-subtitle">DEPUTIES OF THE TIMELINE</p><div className="authority-seal"><Badge size={76} strokeWidth={1}/><span>THE SHERIFF<br/>WANTS YOU.</span></div><p className="wanted-copy">The rich won’t tax themselves.<br/>Every jurisdiction needs its Deputies.</p><div className="paper-rule"/><p className="mono wanted-bottom">FOLLOW THE ORDERS.<br/>EARN YOUR BADGE.<br/>RECRUIT THE NEXT DEPUTY.</p><span className="stamp">RECRUITMENT<br/>IN PROGRESS</span></aside></section>
<div className="ticker"><span>NO TOKEN PROMISE</span><Star size={13}/><span>NO APY</span><Star size={13}/><span>NO EQUITY</span><Star size={13}/><span>JUST VOLUNTARY TAXATION</span></div>
<section className="registry-section wrap" id="registry"><div className="registry-intro"><p className="eyebrow muted">01 / THE DEPUTY REGISTRY</p><h2>The Sheriff<br/>is hiring.</h2><p>You bring the timeline. The Sheriff brings the paperwork.</p><p>Apply with your X username, complete your Field Orders, then claim your numbered Deputy badge. Your recruitment link arrives with your badge.</p><p className="mono accent">ATTENTION → BADGE → RECRUIT → REPEAT</p><div className="registry-note"><Badge size={27}/><p>The first 100 issued badges become<br/><strong>Founding Deputies.</strong></p></div></div><RegistryPanel/></section>
<PublicRecords/>
<section className="tax-code wrap" id="tax-code"><p className="eyebrow">THE TAX CODE / ARTICLE 001</p><h2>No fine print.<br/>Just a very bold premise.</h2><p>Participation is voluntary. There is no token promise, APY, equity, guaranteed airdrop or guaranteed financial return. Phase I targets $75,000 with contributions of $750–$2,500. Phase II targets $25,000 with contributions of $25–$250 and stays locked until Phase I reaches its target.</p></section></main><footer className="wrap"><span>THE DECENTRALIZED REVENUE SERVICE</span><span>JURISDICTION: THE ENTIRE TIMELINE.</span></footer></>;
}
